### ISSUE TITLE
Python error...

### ISSUE THREAD

**Issue by divit0n** [fipso/RewardsGG-Bot#1]
I cant even instal pycurl on windows 10 x64.. 
http://screenshot.sh/m7VOjzYforrT8
but but the application must be great... :)

**Comment by fipso** [comment]
Maybe you should upgrade your Python to 3.5.

**Comment by fipso** [comment]
To install pycurl correctly run 'pip install pycurl' in an Administrator cmd

**Comment by fipso** [comment]
Is it working now ?
